### PR TITLE
Few changes to make this work with latest Appium

### PR DESCRIPTION
**Pull request by eriam**
Just like that !

Let me know how it goes.

Thanks

### CODE REVIEW

**Review by jlipps — APPROVED** [review]

**Comment by jlipps** [comment]
Hi there, thanks for this! It looks like your latest commit was added with an e-mail address github doesn't associate with your user, so the CLA check has failed. Are you able to rebase with your github user e-mail?

**Comment by eriam** [comment]
Hello Jonathan

I made some git mess trying to revert the commit -- is that ok with this revert (that I've done twice ..) ?

Thanks

Eriam

**Comment by jlipps** [comment]
Hmm, it's still not working. It's usually better to do a squash & rebase than a revert. At this point the history is so mangled what I'd recommend is this: make a new git repo clone. Then copy the current clone with your changes on top of it (making sure not to copy the `.git` directory inside. That should give you a modified state in the new clone that enables you to make just one commit. Then you can close this PR and open up a new PR from that checkout. make sense?

**Comment by eriam** [comment]
Forced, cleaned and squashed -- thanks for your patience ! Is that better like this ?

**Comment by jlipps** [comment]
perfect!

**Pull request merged**
